// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSisyqj6-LRUuh7djUsj7lDkp7wzwBuBA',
    appId: '1:801425042995:web:28f7708310bb6b4ec9fd46',
    messagingSenderId: '801425042995',
    projectId: 'vet-me-ca2f7',
    authDomain: 'vet-me-ca2f7.firebaseapp.com',
    storageBucket: 'vet-me-ca2f7.appspot.com',
    measurementId: 'G-GK5VRQ1VDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8YImJIk-UAyAPVJ3GBJXa1Ul9q-FWYw',
    appId: '1:801425042995:android:5882f76467e5d16dc9fd46',
    messagingSenderId: '801425042995',
    projectId: 'vet-me-ca2f7',
    storageBucket: 'vet-me-ca2f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_Cv6nCi7GfU1f1XSgrIDocdSkor-WRo',
    appId: '1:801425042995:ios:61e282ba8052af36c9fd46',
    messagingSenderId: '801425042995',
    projectId: 'vet-me-ca2f7',
    storageBucket: 'vet-me-ca2f7.appspot.com',
    iosClientId: '801425042995-32j7ebvh6vbrs0nph3nocuqovsc4n79a.apps.googleusercontent.com',
    iosBundleId: 'com.vetme.madCw2VetMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_Cv6nCi7GfU1f1XSgrIDocdSkor-WRo',
    appId: '1:801425042995:ios:61e282ba8052af36c9fd46',
    messagingSenderId: '801425042995',
    projectId: 'vet-me-ca2f7',
    storageBucket: 'vet-me-ca2f7.appspot.com',
    iosClientId: '801425042995-32j7ebvh6vbrs0nph3nocuqovsc4n79a.apps.googleusercontent.com',
    iosBundleId: 'com.vetme.madCw2VetMe',
  );
}
